- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobBasinTech
  requirements:
    - !type:DepartmentTimeRequirement
     department: Cargo
     time: 1800 # 1 hr
  icon: "JobIconShaftMiner"
  startingGear: PilotGear
  supervisors: job-supervisors-qm
  access:
  - Salvage
  - Maintenance
  - External
  - Cargo 
  special:
  - !type:AddComponentSpecial
    components:
    - type: ExpedPilot # Allows them to use their mech

- type: startingGear
  id: PilotGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    id: PilotPDA
    ears: ClothingHeadsetCargo
    outerClothing: ClothingOuterCoatBomber
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatHardhatArmored # protect the pilot
    shoes: ClothingShoesLeather
    back: ClothingBackpackSatchelLeather

- type: roleLoadout
  id: JobPilot
  groups:
  - GroupTankHarness
  - Survival
  - GroupSpeciesBreathTool

