- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3600 # 1 hr
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access: # TP - Removed Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetMining # TP
  #storage:
    #back:
    #- Stuff





# Back
- type: loadout
  id: SalvageSpecialistBackpack
  equipment:
    back: ClothingBackpackSalvage

- type: loadout
  id: SalvageSpecialistSatchel
  equipment:
    back: ClothingBackpackSatchelSalvage

- type: loadout
  id: SalvageSpecialistDuffel
  equipment:
    back: ClothingBackpackDuffelSalvage

# OuterClothing
- type: loadout
  id: SalvageSpecialistWintercoat
  equipment:
    outerClothing: ClothingOuterWinterMiner

# Shoes
- type: loadout
  id: SalvageBoots
  equipment:
    shoes: ClothingShoesBootsSalvage
